# Generated by Django 5.0.7 on 2025-04-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_bid_created_at_alter_bid_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animals",
            name="imageUrl",
        ),
        migrations.AddField(
            model_name="animals",
            name="imageFile",
            field=models.ImageField(blank=True, null=True, upload_to="animals/"),
        ),
    ]
